services:
  postgres:
    image: 'postgres:latest'
    hostname: db-postgresql
    environment:
      - 'POSTGRES_DB=post_tech_db'
      - 'POSTGRES_PASSWORD=root'
      - 'POSTGRES_USER=root'
    ports:
      - '5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s