services:
  app:
    build:
      context: .
    hostname: app
    image: robsonbnh/xxxx
    environment:
      - SERVER_PORT=8080
      - DATABASE_URL=jdbc:postgresql://db-postgresql:5432/pos_tech_db
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
    depends_on:
      db-postgresql:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - pos-tech

  db-postgresql:
    image: postgres:latest
    hostname: db-postgresql
    environment:
      - POSTGRES_DB=post_tech_db
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    networks:
      - pos-tech