services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: app
#    image: robsonbnh/tech-challenge:latest
    environment:
      - SERVER_PORT=8080
      - DATABASE_URL=jdbc:postgresql://db-postgresql:5432/pos_tech_db
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=root
    depends_on:
      db-postgresql:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - pos-tech
    command: /bin/sh -c "./gradlew clean build && java -jar build/libs/your-app.jar"


  db-postgresql:
    image: postgres:latest
    hostname: db-postgresql
    environment:
      - POSTGRES_DB=pos_tech_db
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "root", "-d", "pos_tech_db"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    networks:
      - pos-tech

networks:
  pos-tech: